apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sai-app-1
  namespace: default
spec:
  interval: 1m
  path: "./repositories/sai-app-1/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: sai-app-1
